### ISSUE TITLE
Menú de Inicio

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-segundo_intento#4]
No habéis entregado el menú de inicio, cuya entrega estaba planificada para el 20 de marzo.

**Comment by oscarperpinan** [comment]
Tras el aviso de @jbustilloe he comprobado nuevamente que el menú de inicio vuelve a estar disponible. Dos comentarios:

1. Soy consciente de que es una versión inicial del programa, pero en su planteamiento actual es algo simple. Os animo a ser más ambiciosos y añadir más funcionalidades. Por otra parte, compruebo que, además del menú de inicio, ya habéis avanzado en su implementación más allá del ritmo que llevamos en la docencia de la asignatura. En este sentido, os recuerdo que uno de los requisitos de la evaluación es el uso de vectores de estructuras.
2. En la interfaz con el usuario, [cuando usáis scanf y comprobáis el resultado](https://github.com/aigora/twE105_1920-segundo_intento/blob/9096effdd964c31ffa61bcf1a8e95087aacc18d2/CINETSIDI.c#L50), es conveniente usar bucles do-while en lugar de while. De esta forma evitaréis el uso duplicado de scanf.

**Comment by jbustilloe** [comment]
Muchas gracias,
Sabemos que por ahora el planteamiento es un poco simple, sin embargo aun nos quedan varias cosas que implementar para las cuales haremos uso de vectores de estructuras.
Por otro lado, ahora cambio los while por do-while.
